#!/bin/sh

### BEGIN INIT INFO
# Provides:          pilights
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the pilights websocket server
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/pilights
NAME=pilights
DESC=pilights

test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions

case "$1" in
  start)
    echo "new stuff"
		echo "Starting $DESC, ok helpfile? " >> /var/log/HELPFILE
		echo -n "Starting $DESC: "
		start-stop-daemon --start --quiet --make-pidfile --pidfile /var/run/$NAME.pid \
		    --exec $DAEMON -- $DAEMON_OPTS || true
		echo "$NAME."
		;;
	stop)
		echo -n "Stopping $DESC: "
		start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid || true
		echo "$NAME: "
    ;;
	restart)
		echo -n "Restarting $DESC: "
		start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid || true
		sleep 1
		start-stop-daemon --start --quiet --make-pidfile --pidfile /var/run/$NAME.pid \
        --exec $DAEMON -- $DAEMON_OPTS || true
		echo "$NAME."
		;;
	status)
		status_of_proc -p /var/run/$NAME.pid "$DAEMON" pilights && exit 0 || exit $?
		;;
  *)
		echo "Usage: $NAME {start|stop|restart|status}" >&2
    exit 3
    ;;
esac
